import type { spanishQuestionLabels } from '../setup_question_translations';

/** French presentation labels; semantic question IDs remain unchanged. */
export const questionLabelsFr: Readonly<Record<keyof typeof spanishQuestionLabels, string>> = {
  'features.issues': 'Automatiser les tickets : branches, étiquettes, projets et cycle de vie',
  'features.pullRequests': 'Automatiser les pull requests : revue, description et cycle de vie',
  'features.commits': 'Automatiser les commits : progression, taille et analyse Bugbot',
  'features.issueComments': 'Répondre aux commentaires des tickets et permettre les corrections Bugbot',
  'features.pullRequestComments': 'Répondre aux commentaires des pull requests et permettre les corrections Bugbot',
  'features.agentProvisioning': 'Vérifier l’installation des agents CLI dans GitHub Actions',
  'features.credentialHealth': 'Vérifier l’état des identifiants distants',
  'features.inactiveIssueClosure': 'Fermer les tickets inactifs après le délai défini',
  'features.issueTemplates': 'Installer les modèles de ticket',
  'features.pullRequestTemplate': 'Installer le modèle de pull request',
  'issueWorkflows.enabled': 'Types de workflows de ticket à activer',
  'repositoryAgentGuidance.enabled': 'Générer des instructions pour les agents dans le dépôt ?',
  'repositoryAgentGuidance.agentsPointer': 'Comment trouver les instructions depuis AGENTS.md',
  'agents.findings.modelProvider': 'Fournisseur de modèle partagé (sauf réglage propre à une tâche)',
  'agents.findings.model': 'Modèle partagé (sauf réglage propre à une tâche)',
  'agents.findings.effort': 'Effort de raisonnement partagé (les réglages par tâche sont conservés)',
  'agents.findings.executable': 'Exécutable partagé validé (les réglages par tâche sont conservés)',
  'agents.configureIndependently': 'Configurer le modèle et la commande séparément pour chaque tâche ?',
  'repository.mainBranch': 'Branche de production',
  'repository.developmentBranch': 'Branche de développement',
  'repository.featureTree': 'Préfixe des branches de fonctionnalité',
  'repository.bugfixTree': 'Préfixe des branches de correction',
  'repository.hotfixTree': 'Préfixe des branches de correctif urgent',
  'repository.releaseTree': 'Préfixe des branches de version',
  'repository.docsTree': 'Préfixe des branches de documentation',
  'repository.choreTree': 'Préfixe des branches de maintenance',
  'repository.issueManagedBranches': 'L’Action peut-elle créer des branches liées aux tickets ?',
  'repository.preBranchSdd': 'Exiger un SDD avant de créer certaines branches ?',
  'repository.reopenIssueOnPush': 'Rouvrir un ticket fermé quand sa branche reçoit des commits ?',
  'repository.desiredAssigneesCount': 'Nombre souhaité de responsables par ticket',
  'repository.desiredReviewersCount': 'Nombre souhaité de réviseurs par pull request',
  'repository.inactivityThresholdHours': 'Heures d’inactivité avant la fermeture d’un ticket en attente',
  'repository.repositoryLocale': 'Langue des messages du dépôt',
  'repository.issueLocale': 'Langue des tickets (vide : hériter)',
  'repository.pullRequestLocale': 'Langue des pull requests (vide : hériter)',
  'repository.commitPrefixTransforms': 'Transformation des préfixes de commit',
  'repository.releaseReconciliationStrategy': 'Stratégie de réconciliation des versions',
  'repository.hotfixReconciliationStrategy': 'Stratégie de réconciliation des correctifs urgents',
  'repository.reconciliationPullRequestMode': 'Mode des pull requests de réconciliation',
  'repository.reconciliationBackmergeMode': 'Mode de fusion de retour',
  'repository.hotfixActiveReleasePolicy': 'Destination du correctif pendant une version active',
  'repository.reconciliationTree': 'Préfixe des branches de réconciliation',
  'repository.reconciliationCleanup': 'Nettoyage des branches après réconciliation',
  'repository.reconciliationIssueCompletion': 'Sort du ticket après réconciliation',
  'repository.orchestrationPresentationMode': 'Niveau de détail du centre de contrôle des versions',
  'repository.orchestrationDiagrams': 'Afficher des diagrammes accessibles pour les versions ?',
  'repository.orchestrationCommentMode': 'Comment publier les commentaires du cycle de version',
  'ai.pullRequestDescriptionMode': 'Comment mettre à jour la description des pull requests',
  'ai.ignoreFiles': 'Fichiers que l’IA doit ignorer',
  'ai.membersOnly': 'Limiter le traitement par IA aux membres du dépôt ?',
  'ai.includeReasoning': 'Inclure des explications supplémentaires du fournisseur ?',
  'ai.bugbotSeverity': 'Gravité minimale des résultats publiés par Bugbot',
  'ai.bugbotCommentLimit': 'Nombre maximal de commentaires Bugbot par exécution',
  'ai.bugbotFixVerifyCommands': 'Commandes de vérification des corrections Bugbot',
  'ai.bugbotDryRun': 'Analyser avec Bugbot sans publier de changements ?',
  'ai.bugbotEffort': 'Profondeur de l’analyse Bugbot',
  'ai.bugbotReviewDrafts': 'Analyser les pull requests en brouillon ?',
  'ai.bugbotTraceRules': 'Indiquer quelles sources de règles ont été appliquées ?',
  'ai.bugbotSuggestedChanges': 'Publier des suggestions de modification sûres ?',
  'ai.bugbotTelemetry': 'Enregistrer des métriques Bugbot sans contenu ?',
  'ai.bugbotFailOnUnresolved': 'Faire échouer la vérification si des résultats restent ouverts ?',
  'ai.bugbotOrganizationRules': 'Règles Bugbot communes, une par ligne',
  'ai.provisioningMode': 'Comment préparer l’agent CLI sur le runner',
  'pullRequestApproval.mode': 'Que peut faire le bot pour approuver les pull requests ?',
  'pullRequestApproval.testChecks': 'Quelles vérifications CI sont fiables pour approuver ?',
  'pullRequestApproval.producerAttested': 'Avez-vous vérifié le job, l’App et l’étape obligatoire de couverture ?',
  'pullRequestApproval.coverage.mode': 'Comment prouver la couverture requise',
  'pullRequestApproval.coverage.checkName': 'Vérification fiable imposant la couverture',
  'pullRequestApproval.coverage.minDiffPercent': 'Couverture minimale des lignes modifiées (0–100)',
  'pullRequestApproval.coverage.artifactWorkflowName': 'Workflow publiant copilot-diff-coverage-v1',
  'pullRequestApproval.coverage.reporterAttested': 'Avez-vous vérifié l’installation du rapporteur numérique ?',
  'projects.enabled': 'Intégrer des Projects GitHub existants ?',
  'projects.ids': 'Choisir des Projects existants ou saisir leurs numéros d’URL',
  'projects.statusVerified': 'Avez-vous vérifié sur GitHub les quatre valeurs Status exactes de chaque Project choisi ?',
  'projects.issueCreatedColumn': 'Valeur Status des nouveaux tickets',
  'projects.pullRequestCreatedColumn': 'Valeur Status des nouvelles pull requests',
  'projects.issueInProgressColumn': 'Valeur Status des tickets en cours',
  'projects.pullRequestInProgressColumn': 'Valeur Status des pull requests en cours',
  createInitialTag: 'Créer v1.0.0 si aucune étiquette de version n’existe ?',
  manageRepositoryVariables: 'Créer ou mettre à jour les Variables GitHub Actions ?',
  manageRepositorySecrets: 'Valider et configurer les Secrets GitHub Actions ?',
};
