import type { spanishQuestionLabels } from '../setup_question_translations';

/** Portuguese presentation labels; semantic question IDs remain unchanged. */
export const questionLabelsPt: Readonly<Record<keyof typeof spanishQuestionLabels, string>> = {
  'features.issues': 'Automatizar questões: ramos, etiquetas, projetos e ciclo de vida',
  'features.pullRequests': 'Automatizar pull requests: revisão, descrição e ciclo de vida',
  'features.commits': 'Automatizar commits: progresso, tamanho e análise do Bugbot',
  'features.issueComments': 'Responder a comentários de questões e permitir correções do Bugbot',
  'features.pullRequestComments': 'Responder a comentários de pull requests e permitir correções do Bugbot',
  'features.agentProvisioning': 'Verificar a instalação dos agentes CLI no GitHub Actions',
  'features.credentialHealth': 'Verificar o estado das credenciais remotas',
  'features.inactiveIssueClosure': 'Fechar questões inativas após o prazo definido',
  'features.issueTemplates': 'Instalar modelos de questão',
  'features.pullRequestTemplate': 'Instalar o modelo de pull request',
  'issueWorkflows.enabled': 'Tipos de fluxo de questões a ativar',
  'repositoryAgentGuidance.enabled': 'Gerar instruções para agentes no repositório?',
  'repositoryAgentGuidance.agentsPointer': 'Como encontrar as instruções a partir de AGENTS.md',
  'agents.findings.modelProvider': 'Fornecedor de modelo partilhado (salvo definição própria de uma tarefa)',
  'agents.findings.model': 'Modelo partilhado (salvo definição própria de uma tarefa)',
  'agents.findings.effort': 'Esforço de raciocínio partilhado (as definições por tarefa são preservadas)',
  'agents.findings.executable': 'Executável partilhado validado (as definições por tarefa são preservadas)',
  'agents.configureIndependently': 'Configurar modelo e comando separadamente para cada tarefa?',
  'repository.mainBranch': 'Ramo de produção',
  'repository.developmentBranch': 'Ramo de desenvolvimento',
  'repository.featureTree': 'Prefixo dos ramos de funcionalidade',
  'repository.bugfixTree': 'Prefixo dos ramos de correção',
  'repository.hotfixTree': 'Prefixo dos ramos de hotfix',
  'repository.releaseTree': 'Prefixo dos ramos de release',
  'repository.docsTree': 'Prefixo dos ramos de documentação',
  'repository.choreTree': 'Prefixo dos ramos de manutenção',
  'repository.issueManagedBranches': 'A Action pode criar ramos associados a questões?',
  'repository.preBranchSdd': 'Exigir um SDD antes de criar determinados ramos?',
  'repository.reopenIssueOnPush': 'Reabrir uma questão fechada quando o seu ramo recebe commits?',
  'repository.desiredAssigneesCount': 'Número pretendido de responsáveis por questão',
  'repository.desiredReviewersCount': 'Número pretendido de revisores por pull request',
  'repository.inactivityThresholdHours': 'Horas de inatividade antes de fechar uma questão em espera',
  'repository.repositoryLocale': 'Idioma das mensagens do repositório',
  'repository.issueLocale': 'Idioma das questões (vazio: herdar)',
  'repository.pullRequestLocale': 'Idioma das pull requests (vazio: herdar)',
  'repository.commitPrefixTransforms': 'Transformação dos prefixos dos commits',
  'repository.releaseReconciliationStrategy': 'Estratégia de reconciliação de releases',
  'repository.hotfixReconciliationStrategy': 'Estratégia de reconciliação de hotfixes',
  'repository.reconciliationPullRequestMode': 'Modo das pull requests de reconciliação',
  'repository.reconciliationBackmergeMode': 'Modo da fusão de retorno',
  'repository.hotfixActiveReleasePolicy': 'Destino do hotfix durante uma release ativa',
  'repository.reconciliationTree': 'Prefixo dos ramos de reconciliação',
  'repository.reconciliationCleanup': 'Limpeza de ramos após a reconciliação',
  'repository.reconciliationIssueCompletion': 'O que fazer à questão após a reconciliação',
  'repository.orchestrationPresentationMode': 'Nível de detalhe do centro de controlo de releases',
  'repository.orchestrationDiagrams': 'Mostrar diagramas acessíveis para releases?',
  'repository.orchestrationCommentMode': 'Como publicar os comentários do ciclo de release',
  'ai.pullRequestDescriptionMode': 'Como atualizar a descrição das pull requests',
  'ai.ignoreFiles': 'Ficheiros que a IA deve ignorar',
  'ai.membersOnly': 'Limitar o processamento por IA aos membros do repositório?',
  'ai.includeReasoning': 'Incluir explicações adicionais do fornecedor?',
  'ai.bugbotSeverity': 'Gravidade mínima dos resultados publicados pelo Bugbot',
  'ai.bugbotCommentLimit': 'Número máximo de comentários do Bugbot por execução',
  'ai.bugbotFixVerifyCommands': 'Comandos de verificação das correções do Bugbot',
  'ai.bugbotDryRun': 'Analisar com o Bugbot sem publicar alterações?',
  'ai.bugbotEffort': 'Profundidade da análise do Bugbot',
  'ai.bugbotReviewDrafts': 'Rever pull requests em rascunho?',
  'ai.bugbotTraceRules': 'Indicar que fontes de regras foram aplicadas?',
  'ai.bugbotSuggestedChanges': 'Publicar sugestões de alteração seguras?',
  'ai.bugbotTelemetry': 'Registar métricas do Bugbot sem conteúdo?',
  'ai.bugbotFailOnUnresolved': 'Fazer falhar a verificação se houver resultados por resolver?',
  'ai.bugbotOrganizationRules': 'Regras Bugbot partilhadas, uma por linha',
  'ai.provisioningMode': 'Como preparar o agente CLI no runner',
  'pullRequestApproval.mode': 'O que pode o bot fazer na aprovação de pull requests?',
  'pullRequestApproval.testChecks': 'Que verificações CI são fiáveis para aprovar?',
  'pullRequestApproval.producerAttested': 'Verificou o job, a App e a etapa obrigatória de cobertura?',
  'pullRequestApproval.coverage.mode': 'Como comprovar a cobertura exigida',
  'pullRequestApproval.coverage.checkName': 'Verificação fiável que exige cobertura',
  'pullRequestApproval.coverage.minDiffPercent': 'Cobertura mínima das linhas alteradas (0–100)',
  'pullRequestApproval.coverage.artifactWorkflowName': 'Workflow que publica copilot-diff-coverage-v1',
  'pullRequestApproval.coverage.reporterAttested': 'Verificou a instalação do relatório numérico?',
  'projects.enabled': 'Integrar Projects GitHub existentes?',
  'projects.ids': 'Selecionar Projects existentes ou introduzir os números dos URL',
  'projects.statusVerified': 'Confirmou no GitHub os quatro valores Status exatos de cada Project escolhido?',
  'projects.issueCreatedColumn': 'Valor Status das novas questões',
  'projects.pullRequestCreatedColumn': 'Valor Status das novas pull requests',
  'projects.issueInProgressColumn': 'Valor Status das questões em curso',
  'projects.pullRequestInProgressColumn': 'Valor Status das pull requests em curso',
  createInitialTag: 'Criar v1.0.0 se ainda não existir uma etiqueta de versão?',
  manageRepositoryVariables: 'Criar ou atualizar as Variables do GitHub Actions?',
  manageRepositorySecrets: 'Validar e configurar os Secrets do GitHub Actions?',
};
