name: Copilot - Branch Sync

on:
  push:
    branches:
      - '**'

jobs:
  branch-sync:
    name: Copilot - Branch Sync
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      - uses: vypdev/copilot@v3
        with:
          single-action: check_branch_sync_action
          token: ${{ secrets.PAT }}
