import type { WebSetupPromptCopyId } from '../../../../src/application/contracts/web_setup_view';

export interface PromptCopy { readonly title: string; readonly description: string; readonly choices?: readonly string[] }

export const promptCopyEn: Readonly<Record<WebSetupPromptCopyId, PromptCopy>> = {
  'repository.confirm': { title: 'Confirm this repository', description: 'This checkout points to {repository} on branch {branch}. Confirm the target before configuring PAT access or files.', choices: ['Yes, this is my repository', 'Stop and choose another checkout'] },
  'setup.depth': { title: 'Choose how much detail to review', description: 'Basic still asks about permissions, security, branch roles, Projects, approval and storage. Selected advanced agent, branch-prefix and Bugbot settings keep their defaults; inspect and edit them in the final plan. Custom asks every applicable question. Neither path applies changes now.', choices: ['Basic guided setup (recommended)', 'Customize every setting'] },
  'setup.environmentPat': { title: 'An environment setup PAT is available', description: 'Its value stays in the CLI process and is never sent to this page. Exiting Copilot cannot unset your parent shell variable.', choices: ['Use the environment PAT', 'Create or enter a different PAT'] },
  'plan.review': { title: 'Review your setup plan', description: 'Inspect the affected files, workflows, Variables and Secret names before approving. No setup changes start by opening this plan.' },
  'workflow.update': { title: 'Update existing workflows?', description: 'These existing workflow files differ from the setup plan: {files}. Keeping them may leave some new settings inactive.', choices: ['Keep existing', 'Update setup-managed workflows'] },
  'setupPat.method': { title: 'How will you provide your setup PAT?', description: 'This temporary PAT authorizes this one setup run. GitHub creates it under your operator account; Copilot cannot revoke it for you.', choices: ['Guided GitHub link', 'Manual PAT'] },
  'setupPat.ownerKind': { title: 'Who owns this repository on GitHub?', description: 'The owner determines which organization permissions may be needed. Check the repository header on GitHub if unsure.', choices: ['Organization', 'Personal account', 'Not sure'] },
  'setupPat.review': { title: 'Review provisional setup PAT permissions', description: 'These grants follow your choices so far. GitHub inspection may add a requirement; you will review any change before setup starts.', choices: ['Continue to GitHub', 'Review setup choices again', 'View full permission table', 'Enter a PAT manually'] },
  'setupPat.entry': { title: 'Temporary setup PAT', description: 'Open GitHub as your operator account, complete 2FA, choose “Only select repositories”, select this repository and copy the generated PAT here. This PAT is for this run only; delete it on GitHub afterwards.' },
  'setupPat.confirmAccount': { title: 'GitHub authenticated the setup PAT as @{account}', description: 'Is this the operator account that should configure this repository? A wrong account must stop before any setup change.', choices: ['Yes, continue', 'No, stop'] },
  'setupPat.confirmWrites': { title: 'Confirm write permissions that GitHub cannot safely test', description: 'Some required write grants cannot be proven without a mutation. Check them in GitHub against the displayed permission table before confirming.', choices: ['No, stop', 'Yes, I checked them'] },
  'botPat.method': { title: 'How will you provide the bot PAT?', description: 'The bot PAT is separate from the setup PAT. It belongs to the account that will run future GitHub Actions and is stored as a Secret after approval.', choices: ['Guided GitHub link', 'Manual PAT'] },
  'botPat.login': { title: 'Expected GitHub bot login', description: 'Enter the bot account login without @. Copilot resolves its numeric GitHub ID and compares it with the PAT owner.' },
  'botPat.entry.guided': { title: '{name} — bot account PAT', description: 'Open GitHub as @{account} (account ID {accountId}), not as the setup operator. Select only this repository, review all grants and paste the PAT here. Suggested expiry: 90 days. An existing Secret value cannot be read back.' },
  'botPat.entry.manual': { title: '{name} — bot account PAT', description: 'Use the bot account, select only the intended repository and review all grants before pasting its PAT. Suggested expiry: 90 days. An existing Secret value cannot be read back.' },
  'credential.apiKey': { title: '{name} — {provider} API key', description: 'Paste the API key for {provider}. It is sent only to this local setup process and, if approved, installed as a GitHub Actions Secret. Existing Secret values cannot be read back.' },
  'credential.existing': { title: 'Existing {name}: {status}', description: 'GitHub cannot reveal the current Secret value. Keep it only if you deliberately accept that its health cannot be verified here; replace or skip it otherwise.', choices: ['Keep existing', 'Replace it', 'Skip this credential'] },
  'apply.confirm': { title: 'Apply this setup now?', description: 'This is the final approval. Local files and selected GitHub resources may change. A partial result may require inspection before retrying.', choices: ['Apply setup', 'Stop without applying'] },
};
