import type { WebSetupPromptCopyId } from '../../../../src/application/contracts/web_setup_view';
import type { PromptCopy } from './en';

export const promptCopyEs: Readonly<Record<WebSetupPromptCopyId, PromptCopy>> = {
  'repository.confirm': { title: 'Confirma el repositorio', description: 'Este checkout apunta a {repository} en la rama {branch}. Comprueba el destino antes de configurar permisos del PAT o archivos.', choices: ['Sí, es mi repositorio', 'Detener y elegir otro checkout'] },
  'setup.depth': { title: 'Elige cuánto detalle quieres revisar', description: 'El modo básico sigue preguntando por permisos, seguridad, ramas, Projects, aprobación y almacenamiento. Algunos ajustes avanzados de agentes, prefijos de rama y Bugbot conservan sus valores predeterminados; podrás revisarlos y editarlos en el plan final. El modo personalizado pregunta por todos los ajustes aplicables. Ninguno aplica cambios todavía.', choices: ['Configuración básica guiada (recomendada)', 'Personalizar todos los ajustes'] },
  'setup.environmentPat': { title: 'Hay un PAT de configuración en el entorno', description: 'El valor permanece en el proceso CLI. Al continuar se comprueba la identidad y se crean, leen y eliminan recursos temporales antes de preparar el plan. La instalación requiere aprobación final. Cerrar Copilot no elimina la variable de la terminal original.', choices: ['Usar el PAT del entorno', 'Crear o introducir otro PAT'] },
  'plan.review': { title: 'Revisa el plan de configuración', description: 'Comprueba los archivos, workflows, Variables y nombres de Secrets antes de aprobar. Abrir el plan no inicia ningún cambio.' },
  'workflow.update': { title: '¿Actualizar los workflows existentes?', description: 'Estos archivos difieren del plan: {files}. Si los conservas, algunos ajustes nuevos podrían no activarse.', choices: ['Conservar los existentes', 'Actualizar los workflows gestionados'] },
  'setupPat.method': { title: '¿Cómo proporcionarás el PAT de configuración?', description: 'Este PAT temporal autoriza una sola ejecución. GitHub lo crea con tu cuenta de operador; Copilot no puede revocarlo por ti.', choices: ['Enlace guiado de GitHub', 'Introducir PAT manualmente'] },
  'setupPat.ownerKind': { title: '¿Quién es propietario de este repositorio en GitHub?', description: 'El propietario determina qué permisos de organización pueden hacer falta. Consulta la cabecera del repositorio en GitHub si dudas.', choices: ['Organización', 'Cuenta personal', 'No lo sé'] },
  'setupPat.review': { title: 'Revisa los permisos provisionales del PAT de configuración', description: 'Estos permisos dependen de tus elecciones. Si gestionas Secrets, el enlace preselecciona Actions, Contents y Workflows en escritura para posibles comprobaciones de credenciales. Esas comprobaciones solo se ejecutan si el plan aprobado las necesita. La inspección de GitHub puede revelar otros requisitos.', choices: ['Continuar en GitHub', 'Revisar de nuevo las opciones', 'Ver la tabla completa de permisos', 'Introducir un PAT manualmente'] },
  'setupPat.entry': { title: 'PAT temporal de configuración', description: 'Abre GitHub con tu cuenta de operador, completa el 2FA, elige «Only select repositories», selecciona este repositorio y pega aquí el PAT generado. Es solo para esta ejecución; elimínalo en GitHub después.' },
  'setupPat.confirmAccount': { title: 'GitHub autenticó el PAT de configuración como @{account}', description: '¿Es la cuenta de operador que debe configurar este repositorio? Una cuenta incorrecta debe detener el proceso antes de cualquier cambio.', choices: ['Sí, continuar', 'No, detener'] },
  'setupPat.confirmUnverifiedAccess': { title: 'Comprueba los permisos del PAT marcados como No verificable', description: 'Los permisos Verificados ya pasaron la comprobación. Compara cada permiso obligatorio No verificable con su ámbito y nivel de acceso en los ajustes del PAT en GitHub. Una consulta de solo lectura no demuestra Escritura; No verificable no significa ausente. Comprueba Projects: lectura solo si esa fila aparece como No verificable. Continúa únicamente tras comprobar todos esos permisos.', choices: ['No, detener', 'Sí, los he comprobado'] },
  'botPat.method': { title: '¿Cómo proporcionarás el PAT del bot?', description: 'Es distinto del PAT de configuración. Pertenece a la cuenta que ejecutará las futuras GitHub Actions y se instalará como Secret tras la aprobación.', choices: ['Enlace guiado de GitHub', 'Introducir PAT manualmente'] },
  'botPat.login': { title: 'Usuario previsto del bot en GitHub', description: 'Introduce el nombre de usuario del bot sin @. Copilot consultará su ID numérico de GitHub y lo comparará con el propietario del PAT.' },
  'botPat.entry.guided': { title: '{name} — PAT de la cuenta bot', description: 'Abre GitHub como @{account} (ID {accountId}), no como operador de setup. Selecciona solo este repositorio, revisa todos los permisos y pega aquí el PAT. Caducidad sugerida: 90 días. El valor de un Secret existente no puede leerse.' },
  'botPat.entry.manual': { title: '{name} — PAT de la cuenta bot', description: 'Usa la cuenta bot, selecciona solo el repositorio previsto y revisa todos los permisos antes de pegar el PAT. Caducidad sugerida: 90 días. El valor de un Secret existente no puede leerse.' },
  'credential.apiKey': { title: '{name} — clave API de {provider}', description: 'Pega la clave API de {provider}. Solo se envía a este proceso local y, si apruebas el plan, se instala como Secret de GitHub Actions. Los valores existentes no pueden leerse.' },
  'credential.existing': { title: '{name} existente: {status}', description: 'GitHub no muestra el valor actual del Secret. Consérvalo solo si aceptas expresamente que aquí no se puede comprobar su estado; de lo contrario, sustitúyelo u omítelo.', choices: ['Conservar', 'Sustituir', 'Omitir esta credencial'] },
  'apply.confirm': { title: '¿Aplicar la configuración ahora?', description: 'Esta es la aprobación final. Pueden cambiar archivos locales y recursos de GitHub seleccionados. Si el resultado es parcial, revísalo antes de reintentar.', choices: ['Aplicar configuración', 'Detener sin aplicar'] },
};
