import type { WebSetupPromptCopyId } from '../../../../src/application/contracts/web_setup_view';
import type { PromptCopy } from './en';

export const promptCopyFr: Readonly<Record<WebSetupPromptCopyId, PromptCopy>> = {
  'repository.confirm': { title: 'Confirmez ce dépôt', description: 'Ce dossier pointe vers {repository}, branche {branch}. Vérifiez la cible avant de configurer les accès PAT ou les fichiers.', choices: ['Oui, c’est mon dépôt', 'Arrêter et choisir un autre dossier'] },
  'setup.depth': { title: 'Choisissez le niveau de détail', description: 'Le parcours de base demande toujours les autorisations, la sécurité, les branches, Projects, l’approbation et le stockage. Certains réglages avancés des agents, préfixes de branche et Bugbot conservent leurs valeurs par défaut ; vous pourrez les examiner et les modifier dans le plan final. Le parcours personnalisé pose toutes les questions applicables. Aucun changement n’est appliqué à ce stade.', choices: ['Configuration de base guidée (recommandée)', 'Personnaliser tous les réglages'] },
  'setup.environmentPat': { title: 'Un PAT de configuration est disponible dans l’environnement', description: 'Sa valeur reste dans le processus CLI et n’est jamais envoyée à cette page. Quitter Copilot ne supprime pas la variable du shell parent.', choices: ['Utiliser le PAT de l’environnement', 'Créer ou saisir un autre PAT'] },
  'plan.review': { title: 'Examinez le plan de configuration', description: 'Vérifiez les fichiers, workflows, Variables et noms de Secrets avant d’approuver. Ouvrir le plan ne lance aucun changement.' },
  'workflow.update': { title: 'Mettre à jour les workflows existants ?', description: 'Ces fichiers diffèrent du plan : {files}. Les conserver peut laisser certains nouveaux réglages inactifs.', choices: ['Conserver les fichiers existants', 'Mettre à jour les workflows gérés'] },
  'setupPat.method': { title: 'Comment fournirez-vous le PAT de configuration ?', description: 'Ce PAT temporaire autorise une seule exécution. GitHub le crée avec votre compte opérateur ; Copilot ne peut pas le révoquer à votre place.', choices: ['Lien GitHub guidé', 'Saisir un PAT manuellement'] },
  'setupPat.ownerKind': { title: 'À qui appartient ce dépôt sur GitHub ?', description: 'Le propriétaire détermine les éventuelles autorisations d’organisation. Consultez l’en-tête du dépôt sur GitHub en cas de doute.', choices: ['Organisation', 'Compte personnel', 'Je ne sais pas'] },
  'setupPat.review': { title: 'Examinez les autorisations provisoires du PAT de configuration', description: 'Ces autorisations suivent vos choix. L’inspection de GitHub peut révéler un besoin supplémentaire ; vous le reverrez avant tout changement.', choices: ['Continuer sur GitHub', 'Revoir les choix de configuration', 'Voir toutes les autorisations', 'Saisir un PAT manuellement'] },
  'setupPat.entry': { title: 'PAT temporaire de configuration', description: 'Ouvrez GitHub avec votre compte opérateur, effectuez la 2FA, choisissez « Only select repositories », sélectionnez ce dépôt puis collez ici le PAT généré. Il ne sert qu’à cette exécution ; supprimez-le sur GitHub ensuite.' },
  'setupPat.confirmAccount': { title: 'GitHub a authentifié le PAT de configuration comme @{account}', description: 'Est-ce bien le compte opérateur autorisé à configurer ce dépôt ? Un autre compte doit arrêter le processus avant tout changement.', choices: ['Oui, continuer', 'Non, arrêter'] },
  'setupPat.confirmWrites': { title: 'Confirmez les droits d’écriture que GitHub ne peut pas vérifier sans changement', description: 'Certains droits d’écriture ne peuvent être prouvés sans modifier des ressources. Comparez-les au tableau affiché sur GitHub avant de confirmer.', choices: ['Non, arrêter', 'Oui, je les ai vérifiés'] },
  'botPat.method': { title: 'Comment fournirez-vous le PAT du bot ?', description: 'Il est distinct du PAT de configuration. Il appartient au compte qui exécutera les futures GitHub Actions et sera installé comme Secret après approbation.', choices: ['Lien GitHub guidé', 'Saisir un PAT manuellement'] },
  'botPat.login': { title: 'Identifiant GitHub attendu pour le bot', description: 'Saisissez l’identifiant du bot sans @. Copilot récupère son ID numérique GitHub et le compare au propriétaire du PAT.' },
  'botPat.entry.guided': { title: '{name} — PAT du compte bot', description: 'Ouvrez GitHub en tant que @{account} (ID {accountId}), pas en tant qu’opérateur. Sélectionnez uniquement ce dépôt, vérifiez tous les droits et collez le PAT ici. Expiration suggérée : 90 jours. La valeur d’un Secret existant ne peut pas être relue.' },
  'botPat.entry.manual': { title: '{name} — PAT du compte bot', description: 'Utilisez le compte bot, sélectionnez uniquement le dépôt voulu et vérifiez tous les droits avant de coller le PAT. Expiration suggérée : 90 jours. La valeur d’un Secret existant ne peut pas être relue.' },
  'credential.apiKey': { title: '{name} — clé API de {provider}', description: 'Collez la clé API de {provider}. Elle est envoyée uniquement au processus local puis, si vous approuvez le plan, installée comme Secret GitHub Actions. Les valeurs existantes ne peuvent pas être relues.' },
  'credential.existing': { title: '{name} existant : {status}', description: 'GitHub ne révèle pas la valeur actuelle du Secret. Ne la conservez que si vous acceptez explicitement de ne pas pouvoir vérifier son état ici ; sinon, remplacez-la ou ignorez-la.', choices: ['Conserver', 'Remplacer', 'Ignorer cet identifiant'] },
  'apply.confirm': { title: 'Appliquer la configuration maintenant ?', description: 'C’est l’approbation finale. Des fichiers locaux et ressources GitHub choisis peuvent changer. Un résultat partiel doit être inspecté avant une nouvelle tentative.', choices: ['Appliquer la configuration', 'Arrêter sans appliquer'] },
};
