import type { WebSetupPromptCopyId } from '../../../../src/application/contracts/web_setup_view';
import type { PromptCopy } from './en';

export const promptCopyPt: Readonly<Record<WebSetupPromptCopyId, PromptCopy>> = {
  "botPat.scopeConflict": {"title": "Resolver o conflito de âmbito do PAT do bot", "description": "O Secret PAT do repositório {repository} tem prioridade sobre o PAT da organização selecionado. Elimine o Secret do repositório no GitHub e peça ao Copilot para verificar novamente, ou altere o âmbito do PAT para este repositório. As suas respostas são preservadas. O Copilot não eliminará nenhum Secret.", "choices": ["Já eliminei o PAT do repositório — verificar novamente", "Guardar o PAT no repositório", "Parar a configuração"]},
  "botPat.scopeConflictUnavailable": {"title": "Resolver o conflito de âmbito do PAT do bot", "description": "O GitHub não permitiu confirmar se o PAT do repositório foi eliminado. O conflito continua por resolver. As suas respostas são preservadas. Verifique o acesso e tente novamente, altere o âmbito do PAT para este repositório ou pare a configuração.", "choices": ["Já eliminei o PAT do repositório — verificar novamente", "Guardar o PAT no repositório", "Parar a configuração"]},
  'botPat.identityMismatch': { title: 'Este PAT pertence a outra conta do GitHub', description: 'O PAT pertence a @{actual}; o bot selecionado é @{expected}. Nenhum Secret do bot foi gravado. As suas respostas e o plano aprovado são mantidos. Elimine o PAT não utilizado no GitHub, mude para @{expected} e escolha entre introduzir outro PAT ou parar a configuração.', choices: ['Introduzir outro PAT do bot', 'Parar a configuração'] },
  'repository.confirm': { title: 'Confirme este repositório', description: 'Esta pasta aponta para {repository}, no ramo {branch}. Confirme o destino antes de configurar acessos PAT ou ficheiros.', choices: ['Sim, é o meu repositório', 'Parar e escolher outra pasta'] },
  'setup.depth': { title: 'Escolha o nível de detalhe', description: 'O percurso básico continua a perguntar sobre permissões, segurança, ramos, Projects, aprovação e armazenamento. Algumas definições avançadas de agentes, prefixos de ramos e Bugbot mantêm os valores predefinidos; poderá revê-las e editá-las no plano final. O percurso personalizado pergunta por todas as definições aplicáveis. Nenhum dos percursos aplica alterações nesta fase.', choices: ['Configuração básica guiada (recomendada)', 'Personalizar todas as definições'] },
  'setup.environmentPat': { title: 'Existe um PAT de configuração no ambiente', description: 'O valor permanece no processo CLI. Continuar inicia a verificação de identidade e testes temporários isolados de criação, leitura e eliminação antes do plano. A instalação exige aprovação final. Sair do Copilot não remove a variável da shell original.', choices: ['Usar o PAT do ambiente', 'Criar ou introduzir outro PAT'] },
  'plan.review': { title: 'Reveja o plano de configuração', description: 'Confirme ficheiros, fluxos, Variables e nomes de Secrets antes de aprovar. Abrir o plano não inicia alterações.', choices: undefined },
  'workflow.update': { title: 'Atualizar os fluxos existentes?', description: 'Estes ficheiros diferem do plano: {files}. Conservá-los pode deixar algumas definições novas inativas.', choices: ['Conservar os existentes', 'Atualizar os fluxos geridos'] },
  'setupPat.method': { title: 'Como irá fornecer o PAT de configuração?', description: 'Este PAT temporário autoriza uma única execução. O GitHub cria-o na sua conta de operador; o Copilot não pode revogá-lo por si.', choices: ['Ligação guiada do GitHub', 'Introduzir PAT manualmente'] },
  'setupPat.ownerKind': { title: 'Quem é o proprietário deste repositório no GitHub?', description: 'O proprietário determina as permissões de organização necessárias. Consulte o cabeçalho do repositório no GitHub se tiver dúvidas.', choices: ['Organização', 'Conta pessoal', 'Não tenho a certeza'] },
  'setupPat.review': { title: 'Reveja as permissões provisórias do PAT de configuração', description: 'Estas permissões seguem as suas escolhas. Ao gerir Secrets, a ligação pré-seleciona Actions, Contents e Workflows em escrita para possíveis verificações de credenciais. Estas verificações só decorrem se o plano aprovado as exigir. A inspeção do GitHub pode revelar outros requisitos.', choices: ['Continuar no GitHub', 'Rever as escolhas', 'Ver a tabela completa de permissões', 'Introduzir um PAT manualmente'] },
  'setupPat.entry': { title: 'PAT temporário de configuração', description: 'Abra o GitHub com a sua conta de operador, conclua a 2FA, escolha «Only select repositories», selecione este repositório e cole aqui o PAT gerado. É apenas para esta execução; elimine-o no GitHub depois.' },
  'setupPat.confirmAccount': { title: 'O GitHub autenticou o PAT de configuração como @{account}', description: 'É esta a conta de operador que deve configurar o repositório? Uma conta errada tem de parar o processo antes de qualquer alteração.', choices: ['Sim, continuar', 'Não, parar'] },
  'setupPat.confirmUnverifiedAccess': { title: 'Verifique as permissões do PAT marcadas Não verificável', description: 'As linhas Verificadas já passaram na verificação. Compare cada permissão necessária Não verificável com o âmbito e o nível de acesso nas definições do PAT no GitHub. Uma consulta só de leitura não prova Escrita; Não verificável não significa ausente. Verifique Projects: leitura apenas se essa linha estiver Não verificável. Continue só depois de verificar todas essas permissões.', choices: ['Não, parar', 'Sim, já as verifiquei'] },
  'botPat.method': { title: 'Como irá fornecer o PAT do bot?', description: 'É diferente do PAT de configuração. Pertence à conta que executará as futuras GitHub Actions e será instalado como Secret após aprovação.', choices: ['Ligação guiada do GitHub', 'Introduzir PAT manualmente'] },
  'botPat.login': { title: 'Utilizador GitHub esperado para o bot', description: 'Introduza o nome de utilizador do bot sem @. O Copilot consulta o ID numérico do GitHub e compara-o com o proprietário do PAT.' },
  'botPat.entry.guided': { title: '{name} — PAT da conta bot', description: 'Abra o GitHub como @{account} (ID {accountId}), não como operador. Selecione apenas este repositório, reveja todas as permissões e cole aqui o PAT. Validade sugerida: 90 dias. Não é possível voltar a ler o valor de um Secret existente.' },
  'botPat.entry.manual': { title: '{name} — PAT da conta bot', description: 'Use a conta bot, selecione apenas o repositório pretendido e reveja todas as permissões antes de colar o PAT. Validade sugerida: 90 dias. Não é possível voltar a ler o valor de um Secret existente.' },
  'credential.apiKey': { title: '{name} — chave API de {provider}', description: 'Cole a chave API de {provider}. Só é enviada para este processo local e, se aprovar o plano, instalada como Secret do GitHub Actions. Os valores existentes não podem voltar a ser lidos.' },
  'credential.existing': { title: '{name} existente: {status}', description: 'O GitHub não revela o valor atual do Secret. Conserve-o apenas se aceitar expressamente que aqui não se pode verificar o seu estado; caso contrário, substitua-o ou ignore-o.', choices: ['Conservar', 'Substituir', 'Ignorar esta credencial'] },
  'apply.confirm': { title: 'Aplicar a configuração agora?', description: 'Esta é a aprovação final. Ficheiros locais e recursos GitHub selecionados podem mudar. Um resultado parcial exige inspeção antes de tentar novamente.', choices: ['Aplicar configuração', 'Parar sem aplicar'] },
  'management.token': {"title": "PAT temporário de setup", "description": "Leia a configuração GitHub com um PAT. A leitura basta para inspecionar; alterações exigem Variables Write e aprovação separada. Apenas nomes dos Secrets. Deixe vazio para voltar ao painel."},
  'management.tokenWrite': {"title": "PAT de setup para este ajuste", "description": "Use Variables Write no scope revisto. Após aprovação, a verificação cria e elimina uma Variable temporária. Deixe vazio para voltar ao painel."},
};
