export const planWarningsEn = {
  'No issue workflow kind is enabled; issue events will remain unmanaged until a supported Issue Form and profile entry are enabled.': 'No issue workflow kind is enabled; issue events will remain unmanaged until a supported Issue Form and profile entry are enabled.',
  'Help / question issues remain branchless even when issue-managed-branches is enabled.': 'Help / question issues remain branchless even when issue-managed-branches is enabled.',
  'Release automation is installed, but release issue events are disabled by the selected issue workflow profile.': 'Release automation is installed, but release issue events are disabled by the selected issue workflow profile.',
  'Hotfix automation is installed, but hotfix issue events are disabled by the selected issue workflow profile.': 'Hotfix automation is installed, but hotfix issue events are disabled by the selected issue workflow profile.',
  'Repository agent guidance generation is disabled; collaborators will not receive the generated profile or workflow skill.': 'Repository agent guidance generation is disabled; collaborators will not receive the generated profile or workflow skill.',
  'Release and hotfix workflows require the workflow PAT Secret and a writable token.': 'Release and hotfix workflows require the workflow PAT Secret and a writable token.',
  'Merge queue mode fails closed unless every required producer is verified automatically or covered by an exact reviewed attestation.': 'Merge queue mode fails closed unless every required producer is verified automatically or covered by an exact reviewed attestation.',
  'Inactive issue closure is enabled; waiting issues are closed after the configured inactivity threshold and can be reopened with a new comment.': 'Inactive issue closure is enabled; waiting issues are closed after the configured inactivity threshold and can be reopened with a new comment.',
  'Selected Project numbers must be accessible to the bot PAT, and all four configured Status values must exist in every selected Project.': 'Selected Project numbers must be accessible to the bot PAT, and all four configured Status values must exist in every selected Project.',
  'Cursor is an experimental runtime in Copilot and requires a compatible CLI plus CURSOR_API_KEY; the Action installs the official CLI when the default executable is absent.': 'Cursor is an experimental runtime in Copilot and requires a compatible CLI plus CURSOR_API_KEY; the Action installs the official CLI when the default executable is absent.',
  'Organization-level Secrets and Variables require organization permissions; selected access is the safest default and repository values take precedence.': 'Organization-level Secrets and Variables require organization permissions; selected access is the safest default and repository values take precedence.',
} as const;
