import type { planWarningsEn } from './en';

export const planWarningsEs: Readonly<Record<keyof typeof planWarningsEn, string>> = {
  'No issue workflow kind is enabled; issue events will remain unmanaged until a supported Issue Form and profile entry are enabled.': 'No has activado ningún tipo de flujo de incidencias. Sus eventos no se gestionarán hasta que actives un formulario de incidencia y su entrada en el perfil.',
  'Help / question issues remain branchless even when issue-managed-branches is enabled.': 'Las incidencias de ayuda y consulta no crean ramas, aunque actives las ramas gestionadas por incidencias.',
  'Release automation is installed, but release issue events are disabled by the selected issue workflow profile.': 'Se instalará la automatización de versiones, pero el perfil elegido desactiva los eventos de incidencias de versiones.',
  'Hotfix automation is installed, but hotfix issue events are disabled by the selected issue workflow profile.': 'Se instalará la automatización de correcciones urgentes, pero el perfil elegido desactiva los eventos de sus incidencias.',
  'Repository agent guidance generation is disabled; collaborators will not receive the generated profile or workflow skill.': 'Has desactivado la generación de instrucciones para agentes del repositorio. Los colaboradores no recibirán el perfil ni la guía del flujo de trabajo generados.',
  'Release and hotfix workflows require the workflow PAT Secret and a writable token.': 'Los flujos de versiones y correcciones urgentes requieren el Secret con el PAT de la Action y un token con permisos de escritura.',
  'Merge queue mode fails closed unless every required producer is verified automatically or covered by an exact reviewed attestation.': 'La cola de merge bloqueará la operación si cada productor obligatorio no se verifica automáticamente o no dispone de una certificación exacta revisada.',
  'Always-provision mode reinstalls only default Codex/OpenCode runtimes from pinned manifest packages; explicit executables are never replaced and Cursor must be preinstalled.': 'El modo de provisión permanente solo reinstala los entornos predeterminados de Codex y OpenCode desde paquetes fijados en el manifiesto. No sustituye ejecutables explícitos; Cursor debe estar instalado previamente.',
  'Inactive issue closure is enabled; waiting issues are closed after the configured inactivity threshold and can be reopened with a new comment.': 'Está activado el cierre de incidencias inactivas. Las que estén en espera se cerrarán tras el plazo configurado y podrán reabrirse con un comentario.',
  'Selected Project numbers must be accessible to the bot PAT, and all four configured Status values must exist in every selected Project.': 'El PAT del bot debe tener acceso a los Projects seleccionados, y los cuatro valores de Status configurados deben existir en cada uno de ellos.',
  'Cursor is an experimental runtime in Copilot and requires a compatible preinstalled CLI plus CURSOR_API_KEY; Copilot has no automatic Cursor installer.': 'Cursor es un entorno experimental en Copilot. Requiere una CLI compatible ya instalada y CURSOR_API_KEY; Copilot no instala Cursor automáticamente.',
  'Organization-level Secrets and Variables require organization permissions; selected access is the safest default and repository values take precedence.': 'Los Secrets y Variables de organización requieren permisos en ella. Limitar el acceso a los repositorios elegidos es la opción más segura; los valores del repositorio tienen prioridad.',
};
