import type { planWarningsEn } from './en';

export const planWarningsFr: Readonly<Record<keyof typeof planWarningsEn, string>> = {
  'No issue workflow kind is enabled; issue events will remain unmanaged until a supported Issue Form and profile entry are enabled.': 'Aucun type de flux de travail pour les tickets n’est activé. Leurs événements ne seront pas gérés tant qu’un formulaire de ticket pris en charge et son entrée de profil ne seront pas activés.',
  'Help / question issues remain branchless even when issue-managed-branches is enabled.': 'Les tickets d’aide ou de question ne créent pas de branche, même lorsque les branches gérées par les tickets sont activées.',
  'Release automation is installed, but release issue events are disabled by the selected issue workflow profile.': 'L’automatisation des versions est déjà installée, mais le profil choisi désactive les événements des tickets de version.',
  'Hotfix automation is installed, but hotfix issue events are disabled by the selected issue workflow profile.': 'L’automatisation des correctifs urgents est déjà installée, mais le profil choisi désactive les événements des tickets correspondants.',
  'Repository agent guidance generation is disabled; collaborators will not receive the generated profile or workflow skill.': 'La génération des consignes pour les agents du dépôt est désactivée. Les collaborateurs ne recevront ni le profil ni le guide de flux de travail générés.',
  'Release and hotfix workflows require the workflow PAT Secret and a writable token.': 'Les flux de version et de correctif urgent nécessitent le Secret contenant le PAT de l’Action et un jeton autorisé à écrire.',
  'Merge queue mode fails closed unless every required producer is verified automatically or covered by an exact reviewed attestation.': 'La file de fusion bloque l’opération si chaque producteur requis n’est pas vérifié automatiquement ou couvert par une attestation exacte et examinée.',
  'Always-provision mode reinstalls only default Codex/OpenCode runtimes from pinned manifest packages; explicit executables are never replaced and Cursor must be preinstalled.': 'Le mode de provisionnement permanent ne réinstalle que les environnements Codex et OpenCode par défaut depuis les paquets verrouillés du manifeste. Il ne remplace jamais les exécutables indiqués explicitement ; Cursor doit être préinstallé.',
  'Inactive issue closure is enabled; waiting issues are closed after the configured inactivity threshold and can be reopened with a new comment.': 'La fermeture des tickets inactifs est activée. Les tickets en attente seront fermés après le délai configuré et pourront être rouverts par un nouveau commentaire.',
  'Selected Project numbers must be accessible to the bot PAT, and all four configured Status values must exist in every selected Project.': 'Le PAT du bot doit avoir accès aux Projects sélectionnés, et les quatre valeurs Status configurées doivent exister dans chacun de ces Projects.',
  'Cursor is an experimental runtime in Copilot and requires a compatible preinstalled CLI plus CURSOR_API_KEY; Copilot has no automatic Cursor installer.': 'Cursor est un environnement expérimental dans Copilot. Il nécessite une CLI compatible déjà installée et CURSOR_API_KEY ; Copilot ne l’installe pas automatiquement.',
  'Organization-level Secrets and Variables require organization permissions; selected access is the safest default and repository values take precedence.': 'Les Secrets et Variables d’organisation nécessitent des droits sur celle-ci. Limiter l’accès aux dépôts sélectionnés est le choix le plus sûr ; les valeurs du dépôt prévalent.',
};
