import type { CatalogMessage } from '../../domain/message_catalog';

export const APPROVAL_DOCTOR_MESSAGE_IDS = Object.freeze([
  'doctor.approval.policyInvalid', 'doctor.approval.policyInvalidAction',
  'doctor.approval.overallInvalid', 'doctor.approval.overallInvalidAction',
  'doctor.approval.policyUnverified', 'doctor.approval.policyUnverifiedAction',
  'doctor.approval.policyMissing', 'doctor.approval.policyMissingAction',
  'doctor.approval.policyOff', 'doctor.approval.policyOffAction',
  'doctor.approval.policyInstalled',
  'doctor.approval.dependencySkipped', 'doctor.approval.dependencySkippedAction',
  'doctor.approval.overallOff', 'doctor.approval.overallOffAction',
  'doctor.approval.workflowReady', 'doctor.approval.workflowMissing', 'doctor.approval.workflowAction',
  'doctor.approval.botMissing', 'doctor.approval.botHealthyUnverified',
  'doctor.approval.botUnverified', 'doctor.approval.botAction',
  'doctor.approval.rulesReady', 'doctor.approval.rulesUnsafe', 'doctor.approval.rulesAction',
  'doctor.approval.producersReady', 'doctor.approval.producersUnsafe', 'doctor.approval.producersAction',
  'doctor.approval.numericAttested', 'doctor.approval.numericUnattested', 'doctor.approval.numericAction',
  'doctor.approval.bugbotReady', 'doctor.approval.bugbotUnsafe', 'doctor.approval.bugbotAction',
  'doctor.approval.overallReady', 'doctor.approval.overallNotReady', 'doctor.approval.overallAction',
] as const);

export type ApprovalDoctorMessageId = typeof APPROVAL_DOCTOR_MESSAGE_IDS[number];

export const ENGLISH_APPROVAL_DOCTOR_MESSAGES: Readonly<Record<ApprovalDoctorMessageId, CatalogMessage>> = Object.freeze({
  'doctor.approval.policyInvalid': 'Installed PR approval policy is invalid or has an unknown version.',
  'doctor.approval.policyInvalidAction': 'Run copilot setup with a supported policy.',
  'doctor.approval.overallInvalid': 'Native approval is blocked by an invalid policy.',
  'doctor.approval.overallInvalidAction': 'Repair the policy and rerun doctor.',
  'doctor.approval.policyUnverified': 'Installed PR approval policy could not be inspected.',
  'doctor.approval.policyUnverifiedAction': 'Validate the setup PAT and rerun doctor.',
  'doctor.approval.policyMissing': 'No policy Variable is installed; native approval is safely off.',
  'doctor.approval.policyMissingAction': 'Run copilot setup to opt in.',
  'doctor.approval.policyOff': 'PR approval is explicitly off.',
  'doctor.approval.policyOffAction': 'Choose recommend or guarded in copilot setup to enable.',
  'doctor.approval.policyInstalled': 'Version 1 {mode} policy is installed.',
  'doctor.approval.dependencySkipped': 'Approval is not enabled by an installed policy.',
  'doctor.approval.dependencySkippedAction': 'Install a validated policy through copilot setup.',
  'doctor.approval.overallOff': 'No native bot approvals can occur; the feature is disabled or unverified.',
  'doctor.approval.overallOffAction': 'Run copilot setup when ready.',
  'doctor.approval.workflowReady': 'Approval observer matches the managed template on the default branch.',
  'doctor.approval.workflowMissing': 'Approval observer is missing, drifted, or not yet installed on the default branch.',
  'doctor.approval.workflowAction': 'Review and install the generated observer on the default branch.',
  'doctor.approval.botMissing': 'Runtime PAT Secret is missing.',
  'doctor.approval.botHealthyUnverified': 'Runtime PAT health passed, but Pull requests write permission cannot be proven by a read-only check.',
  'doctor.approval.botUnverified': 'Runtime PAT identity or Pull requests write capability is not verified.',
  'doctor.approval.botAction': 'Verify the runtime PAT has Pull requests write permission and belongs to a distinct bot account.',
  'doctor.approval.rulesReady': 'Selected branch rules are readable, dismiss stale approvals, and have no approval-check cycle.',
  'doctor.approval.rulesUnsafe': 'Selected branch rules are unsafe or could not be verified; native approval is blocked.',
  'doctor.approval.rulesAction': 'Enable stale-review dismissal, remove Copilot / Approval from required checks, or grant rules read access.',
  'doctor.approval.producersReady': 'Producer workflow names are active and their exact check/App identity and coverage gate were operator-attested; runtime rechecks current-head evidence.',
  'doctor.approval.producersUnsafe': 'One or more exact test/coverage producers are missing or not attested.',
  'doctor.approval.producersAction': 'Select active exact producers and attest their App identity and coverage-enforcing step in copilot setup.',
  'doctor.approval.numericAttested': 'Numeric reporter installation is attested, but output cannot be verified without a current PR artifact.',
  'doctor.approval.numericUnattested': 'Numeric coverage reporter installation has not been attested.',
  'doctor.approval.numericAction': 'Install the reporter in trusted CI, attest it in setup, and verify a bounded copilot-diff-coverage-v1 artifact on a test PR.',
  'doctor.approval.bugbotReady': 'Bugbot can produce complete info-level, non-dry-run evidence.',
  'doctor.approval.bugbotUnsafe': 'Bugbot configuration hides or omits evidence needed for approval.',
  'doctor.approval.bugbotAction': 'Enable telemetry, disable dry-run, and use info severity.',
  'doctor.approval.overallReady': 'Future eligible human PRs can be assessed for guarded approval.',
  'doctor.approval.overallNotReady': 'Native approval is not ready; existing PRs and reviews are unchanged.',
  'doctor.approval.overallAction': 'Resolve the named approval checks and rerun doctor.',
});

export const SPANISH_APPROVAL_DOCTOR_MESSAGES: Readonly<Record<ApprovalDoctorMessageId, CatalogMessage>> = Object.freeze({
  'doctor.approval.policyInvalid': 'La política de aprobación instalada es inválida o tiene una versión desconocida.',
  'doctor.approval.policyInvalidAction': 'Ejecuta copilot setup con una política compatible.',
  'doctor.approval.overallInvalid': 'La aprobación nativa está bloqueada por una política inválida.',
  'doctor.approval.overallInvalidAction': 'Corrige la política y vuelve a ejecutar doctor.',
  'doctor.approval.policyUnverified': 'No se pudo inspeccionar la política de aprobación instalada.',
  'doctor.approval.policyUnverifiedAction': 'Comprueba el PAT de setup y vuelve a ejecutar doctor.',
  'doctor.approval.policyMissing': 'No hay Variable de política; la aprobación nativa está desactivada de forma segura.',
  'doctor.approval.policyMissingAction': 'Ejecuta copilot setup para activarla.',
  'doctor.approval.policyOff': 'La aprobación de PR está desactivada explícitamente.',
  'doctor.approval.policyOffAction': 'Elige recommend o guarded en copilot setup para activarla.',
  'doctor.approval.policyInstalled': 'Está instalada la política versión 1 en modo {mode}.',
  'doctor.approval.dependencySkipped': 'No hay una política instalada que active la aprobación.',
  'doctor.approval.dependencySkippedAction': 'Instala una política validada con copilot setup.',
  'doctor.approval.overallOff': 'No puede haber aprobaciones nativas del bot; la función está desactivada o sin verificar.',
  'doctor.approval.overallOffAction': 'Ejecuta copilot setup cuando esté todo preparado.',
  'doctor.approval.workflowReady': 'El observador coincide con la plantilla gestionada en la rama por defecto.',
  'doctor.approval.workflowMissing': 'El observador falta, difiere o todavía no está instalado en la rama por defecto.',
  'doctor.approval.workflowAction': 'Revisa e instala el observador generado en la rama por defecto.',
  'doctor.approval.botMissing': 'Falta el Secret PAT de ejecución.',
  'doctor.approval.botHealthyUnverified': 'El PAT de ejecución está sano, pero una comprobación de solo lectura no puede demostrar el permiso de escritura sobre PRs.',
  'doctor.approval.botUnverified': 'No se ha verificado la identidad del PAT de ejecución ni su permiso de escritura sobre PRs.',
  'doctor.approval.botAction': 'Comprueba que el PAT permita escribir revisiones de PR y pertenezca a una cuenta de bot distinta.',
  'doctor.approval.rulesReady': 'Las reglas de rama se pueden leer, descartan aprobaciones antiguas y no contienen ciclos con el check de aprobación.',
  'doctor.approval.rulesUnsafe': 'Las reglas de rama no son seguras o no se pudieron verificar; la aprobación nativa está bloqueada.',
  'doctor.approval.rulesAction': 'Activa el descarte de revisiones antiguas, quita Copilot / Approval de los checks obligatorios o concede acceso de lectura a las reglas.',
  'doctor.approval.producersReady': 'Los workflows productores están activos y se ha atestiguado su check, App y paso de cobertura; la ejecución volverá a comprobar la revisión actual.',
  'doctor.approval.producersUnsafe': 'Faltan productores de test/cobertura o no se han atestiguado.',
  'doctor.approval.producersAction': 'Selecciona los productores exactos activos y atestigua la App y el paso obligatorio de cobertura en copilot setup.',
  'doctor.approval.numericAttested': 'Se ha atestiguado el reporter numérico, pero no se puede verificar su salida sin un artefacto de una PR actual.',
  'doctor.approval.numericUnattested': 'No se ha atestiguado la instalación del reporter de cobertura numérica.',
  'doctor.approval.numericAction': 'Instala el reporter en CI de confianza, atestígualo en setup y comprueba un artefacto copilot-diff-coverage-v1 en una PR de prueba.',
  'doctor.approval.bugbotReady': 'Bugbot puede producir evidencias completas con severidad info y sin dry-run.',
  'doctor.approval.bugbotUnsafe': 'La configuración de Bugbot oculta u omite evidencias necesarias para aprobar.',
  'doctor.approval.bugbotAction': 'Activa telemetría, desactiva dry-run y usa severidad info.',
  'doctor.approval.overallReady': 'Las futuras PRs humanas elegibles pueden evaluarse para aprobación protegida.',
  'doctor.approval.overallNotReady': 'La aprobación nativa no está lista; las PRs y revisiones existentes no cambian.',
  'doctor.approval.overallAction': 'Resuelve las comprobaciones de aprobación indicadas y vuelve a ejecutar doctor.',
});
