import type { AgentConfiguration } from '../../domain/agent';
import {
  MESSAGE_CATALOG_VERSION,
  type CatalogMessage,
  type MessageCatalogDefinition,
} from '../../domain/message_catalog';
import type { MessageCatalogResolutionPort } from '../ports/message_catalog_ports';
import {
  resolveMessageCatalogView,
  resolveStaticMessageCatalogView,
  type ResolvedMessageCatalogView,
} from './resolved_message_catalog_policy';
import {
  ENGLISH_MERGE_QUEUE_MESSAGES,
  MERGE_QUEUE_MESSAGE_IDS,
  SPANISH_MERGE_QUEUE_MESSAGES,
  type MergeQueueMessageId,
} from './merge_queue_message_catalog';
import {
  APPROVAL_DOCTOR_MESSAGE_IDS,
  ENGLISH_APPROVAL_DOCTOR_MESSAGES,
  SPANISH_APPROVAL_DOCTOR_MESSAGES,
  type ApprovalDoctorMessageId,
} from './approval_doctor_message_catalog';

const DOCTOR_ONLY_MESSAGE_IDS = Object.freeze([
  'doctor.title',
  'doctor.title.partial',
  'doctor.summary',
  'doctor.noMutation',
  'doctor.blockedBy',
  'doctor.action',
  'doctor.status.pass',
  'doctor.status.warn',
  'doctor.status.fail',
  'doctor.status.skipped',
  'doctor.label.configuration',
  'doctor.label.repositoryRoot',
  'doctor.label.setupPat',
  'doctor.label.githubScopes',
  'doctor.label.repositorySecrets',
  'doctor.label.repositoryVariables',
  'doctor.label.mergeQueue',
  'doctor.label.localeProfile',
  'doctor.label.repositoryLocale',
  'doctor.label.issueLocale',
  'doctor.label.pullRequestLocale',
  'doctor.label.workflow',
  'doctor.label.variable',
  'doctor.label.credential',
  'doctor.label.mergeQueueTarget',
  'doctor.locale.invalid',
  'doctor.locale.invalidAction',
  'doctor.locale.fallback',
  'doctor.locale.fallbackInherited',
  'doctor.locale.resolved',
  'doctor.locale.resolvedInherited',
  'doctor.locale.dynamicAction',
  'doctor.configuration.valid',
  'doctor.configuration.invalid',
  'doctor.configuration.action',
  'doctor.repositoryRoot.valid',
  'doctor.repositoryRoot.invalid',
  'doctor.repositoryRoot.unverified',
  'doctor.repositoryRoot.action',
  'doctor.workflow.skipped',
  'doctor.workflow.matches',
  'doctor.workflow.drift',
  'doctor.workflow.unverified',
  'doctor.workflow.configurationAction',
  'doctor.workflow.repairAction',
  'doctor.workflow.unverifiedAction',
  'doctor.setupPat.valid',
  'doctor.setupPat.invalid',
  'doctor.setupPat.unverified',
  'doctor.setupPat.replaceAction',
  'doctor.setupPat.unverifiedAction',
  'doctor.mergeQueue.skipped',
  'doctor.mergeQueue.skippedAction',
  'doctor.mergeQueue.unverified',
  'doctor.mergeQueue.unverifiedAction',
  'doctor.scope.unverified',
  'doctor.scope.unverifiedAction',
  'doctor.scope.readable',
  'doctor.scope.unavailable',
  'doctor.scope.grantAction',
  'doctor.variable.missing',
  'doctor.variable.configured',
  'doctor.variable.preserved',
  'doctor.variable.different',
  'doctor.variable.action',
  'doctor.secretMetadata.readable',
  'doctor.credential.group.runnerRequired',
  'doctor.credential.group.missing',
  'doctor.credential.group.healthy',
  'doctor.credential.group.invalid',
  'doctor.credential.group.unverified',
  'doctor.credential.group.action',
  'doctor.credential.missing',
  'doctor.credential.valid',
  'doctor.credential.invalid',
  'doctor.credential.unverifiable',
  'doctor.credential.unverified',
  'doctor.credential.action',
  'doctor.skipped.scope',
  'doctor.skipped.scopeAction',
  'doctor.skipped.variables',
  'doctor.skipped.secrets',
  'doctor.skipped.credentials',
  'doctor.skipped.resourceAction',
  'doctor.mergeQueue.configureSupportedAction',
  'doctor.mergeQueue.repairOrAttestAction',
  'doctor.mergeQueue.selectedMode',
  'doctor.mergeQueue.ready',
  'doctor.mergeQueue.targetUnverified',
  'doctor.mergeQueue.targetUnverifiedAction',
  'doctor.mergeQueue.activeRelease',
  'doctor.mergeQueue.staleAttestation',
  'doctor.mergeQueue.staleAttestationAction',
  'doctor.mergeQueue.producer',
  'doctor.mergeQueue.producerAction',
] as const);

type DoctorOnlyMessageId = typeof DOCTOR_ONLY_MESSAGE_IDS[number];
export type SetupDoctorMessageId = DoctorOnlyMessageId | MergeQueueMessageId | ApprovalDoctorMessageId;
export type SetupDoctorMessageCatalog = ResolvedMessageCatalogView<SetupDoctorMessageId>;

export const SETUP_DOCTOR_MESSAGE_IDS: readonly SetupDoctorMessageId[] = Object.freeze([
  ...DOCTOR_ONLY_MESSAGE_IDS,
  ...MERGE_QUEUE_MESSAGE_IDS,
  ...APPROVAL_DOCTOR_MESSAGE_IDS,
]);

const ENGLISH_DOCTOR_MESSAGES: Readonly<Record<DoctorOnlyMessageId, CatalogMessage>> = Object.freeze({
  'doctor.title': 'Copilot Doctor',
  'doctor.title.partial': 'Copilot Doctor — partial diagnosis',
  'doctor.summary': 'Checks: {pass} pass, {warn} warn, {fail} fail, {skipped} skipped.',
  'doctor.noMutation': 'No repository configuration was changed.',
  'doctor.blockedBy': 'Blocked by: {checks}',
  'doctor.action': 'Action: {action}',
  'doctor.status.pass': 'PASS',
  'doctor.status.warn': 'WARN',
  'doctor.status.fail': 'FAIL',
  'doctor.status.skipped': 'SKIP',
  'doctor.label.configuration': 'Configuration',
  'doctor.label.repositoryRoot': 'Repository root',
  'doctor.label.setupPat': 'Setup PAT',
  'doctor.label.githubScopes': 'GitHub Actions scopes',
  'doctor.label.repositorySecrets': 'Repository Secrets',
  'doctor.label.repositoryVariables': 'Repository Variables',
  'doctor.label.mergeQueue': 'Merge queue',
  'doctor.label.localeProfile': 'Locale profile',
  'doctor.label.repositoryLocale': 'Repository locale',
  'doctor.label.issueLocale': 'Issue locale',
  'doctor.label.pullRequestLocale': 'Pull-request locale',
  'doctor.label.workflow': 'Workflow {id}',
  'doctor.label.variable': 'Variable {name}',
  'doctor.label.credential': 'Credential {name}',
  'doctor.label.mergeQueueTarget': 'Merge queue {target}',
  'doctor.locale.invalid': 'Locale capability could not be inspected because locale configuration is invalid.',
  'doctor.locale.invalidAction': 'Correct the locale values and run doctor again.',
  'doctor.locale.fallback': 'Effective locale {locale} could not resolve a complete safe catalog; product copy fell back atomically to en-US.',
  'doctor.locale.fallbackInherited': 'Effective locale {locale} could not resolve a complete safe catalog; product copy fell back atomically to en-US. It inherits the repository locale.',
  'doctor.locale.resolved': 'Effective locale {locale} resolves through the {source} catalog path.',
  'doctor.locale.resolvedInherited': 'Effective locale {locale} resolves through the {source} catalog path. It inherits the repository locale.',
  'doctor.locale.dynamicAction': 'Check that the planner/language agent is ready and returns valid localized copy, then run doctor again.',
  'doctor.configuration.valid': 'Setup configuration is valid.',
  'doctor.configuration.invalid': 'Setup configuration has {count} validation error(s).',
  'doctor.configuration.action': 'Fix the setup configuration and run doctor again.',
  'doctor.repositoryRoot.valid': 'Current directory is the repository root.',
  'doctor.repositoryRoot.invalid': 'Current directory is not the repository root.',
  'doctor.repositoryRoot.unverified': 'Repository root could not be verified.',
  'doctor.repositoryRoot.action': 'Run doctor from the root of the target Git repository.',
  'doctor.workflow.skipped': 'Workflow comparison was skipped because setup configuration is invalid.',
  'doctor.workflow.matches': 'Matches the installed setup template.',
  'doctor.workflow.drift': 'Local workflow is {state}.',
  'doctor.workflow.unverified': 'Managed workflows could not be compared.',
  'doctor.workflow.configurationAction': 'Fix setup configuration, then run doctor again.',
  'doctor.workflow.repairAction': 'Run setup to repair this managed workflow.',
  'doctor.workflow.unverifiedAction': 'Check local workflow files and run doctor again.',
  'doctor.setupPat.valid': 'The setup PAT is valid.',
  'doctor.setupPat.invalid': 'The setup PAT is invalid.',
  'doctor.setupPat.unverified': 'The setup PAT could not be validated.',
  'doctor.setupPat.replaceAction': 'Replace the setup PAT and run doctor again.',
  'doctor.setupPat.unverifiedAction': 'Check the setup PAT and network access, then run doctor again.',
  'doctor.mergeQueue.skipped': 'Merge-queue readiness was not inspected because setup configuration is invalid.',
  'doctor.mergeQueue.skippedAction': 'Fix the reported configuration errors, then run doctor again.',
  'doctor.mergeQueue.unverified': 'Merge-queue readiness could not be inspected.',
  'doctor.mergeQueue.unverifiedAction': 'Check branch policy access and run doctor again.',
  'doctor.scope.unverified': 'GitHub Actions resource scopes could not be inspected.',
  'doctor.scope.unverifiedAction': 'Check setup PAT access to repository and organization Actions metadata, then retry.',
  'doctor.scope.readable': 'GitHub Actions resource scopes are readable.',
  'doctor.scope.unavailable': 'Some organization-level GitHub Actions resource scopes are unavailable.',
  'doctor.scope.grantAction': 'Grant the setup PAT the required organization Actions metadata access.',
  'doctor.variable.missing': 'Variable is missing.',
  'doctor.variable.configured': 'Variable is configured at {scope} scope.',
  'doctor.variable.preserved': 'Variable differs but is intentionally preserved at {scope} scope.',
  'doctor.variable.different': 'Variable differs from the expected setup configuration.',
  'doctor.variable.action': 'Run setup to reconcile this Variable.',
  'doctor.secretMetadata.readable': 'GitHub Actions Secret metadata is readable.',
  'doctor.credential.group.runnerRequired': 'No fallback Secret is configured; runner authentication must satisfy this group.',
  'doctor.credential.group.missing': 'No alternative credential is present.',
  'doctor.credential.group.healthy': 'At least one alternative credential is healthy.',
  'doctor.credential.group.invalid': 'Every available alternative credential is invalid.',
  'doctor.credential.group.unverified': 'An alternative credential is present, but remote health is unavailable.',
  'doctor.credential.group.action': 'Configure and validate one credential for this requirement group.',
  'doctor.credential.missing': 'Required Secret is missing.',
  'doctor.credential.valid': 'Credential health is valid.',
  'doctor.credential.invalid': 'Credential health is invalid.',
  'doctor.credential.unverifiable': 'Credential health cannot be verified automatically.',
  'doctor.credential.unverified': 'Secret is present, but remote health is unavailable.',
  'doctor.credential.action': 'Configure or replace {name}, then rerun credential health.',
  'doctor.skipped.scope': 'Resource-scope inspection requires a valid setup PAT.',
  'doctor.skipped.scopeAction': 'Replace the setup PAT.',
  'doctor.skipped.variables': 'Variable checks could not run.',
  'doctor.skipped.secrets': 'Secret metadata checks could not run.',
  'doctor.skipped.credentials': 'Credential health could not run.',
  'doctor.skipped.resourceAction': 'Resolve the blocking check and rerun doctor.',
  'doctor.mergeQueue.configureSupportedAction': 'Configure a supported merge-queue producer or choose another reconciliation mode.',
  'doctor.mergeQueue.repairOrAttestAction': 'Repair or attest every required merge-queue producer.',
  'doctor.mergeQueue.selectedMode': 'Selected mode is {mode}; merge-queue producer evidence is not required for this target.',
  'doctor.mergeQueue.ready': 'Ready. {verified} required producer(s) verified automatically and {attested} covered by exact attestation.',
  'doctor.mergeQueue.targetUnverified': 'Target policy could not be inspected because the provider request failed.',
  'doctor.mergeQueue.targetUnverifiedAction': 'Check the setup PAT permissions and target branch policy, then retry.',
  'doctor.mergeQueue.activeRelease': 'Active release branches are discovered dynamically and are revalidated before a hotfix reconciliation branch or pull request is created.',
  'doctor.mergeQueue.staleAttestation': 'This exact attestation does not match a required check observed on production or development.',
  'doctor.mergeQueue.staleAttestationAction': 'Remove the stale attestation or correct its exact check identity.',
  'doctor.mergeQueue.producer': '{verdict}: {state}',
  'doctor.mergeQueue.producerAction': 'Configure or exactly attest this required producer.',
});

const SPANISH_DOCTOR_MESSAGES: Readonly<Record<DoctorOnlyMessageId, CatalogMessage>> = Object.freeze({
  'doctor.title': 'Diagnóstico de Copilot',
  'doctor.title.partial': 'Diagnóstico de Copilot — diagnóstico parcial',
  'doctor.summary': 'Checks: {pass} correctos, {warn} avisos, {fail} fallos, {skipped} omitidos.',
  'doctor.noMutation': 'No se ha cambiado la configuración del repositorio.',
  'doctor.blockedBy': 'Bloqueado por: {checks}',
  'doctor.action': 'Acción: {action}',
  'doctor.status.pass': 'OK',
  'doctor.status.warn': 'AVISO',
  'doctor.status.fail': 'FALLO',
  'doctor.status.skipped': 'OMITIDO',
  'doctor.label.configuration': 'Configuración',
  'doctor.label.repositoryRoot': 'Raíz del repositorio',
  'doctor.label.setupPat': 'PAT de setup',
  'doctor.label.githubScopes': 'Permisos de GitHub Actions',
  'doctor.label.repositorySecrets': 'Secrets del repositorio',
  'doctor.label.repositoryVariables': 'Variables del repositorio',
  'doctor.label.mergeQueue': 'Merge queue',
  'doctor.label.localeProfile': 'Perfil de locale',
  'doctor.label.repositoryLocale': 'Locale del repositorio',
  'doctor.label.issueLocale': 'Locale de issues',
  'doctor.label.pullRequestLocale': 'Locale de pull requests',
  'doctor.label.workflow': 'Workflow {id}',
  'doctor.label.variable': 'Variable {name}',
  'doctor.label.credential': 'Credencial {name}',
  'doctor.label.mergeQueueTarget': 'Merge queue {target}',
  'doctor.locale.invalid': 'No se ha podido inspeccionar la localización porque la configuración de locale no es válida.',
  'doctor.locale.invalidAction': 'Corrige los valores de locale y vuelve a ejecutar doctor.',
  'doctor.locale.fallback': 'El locale efectivo {locale} no ha podido resolver un catálogo completo y seguro; el texto de producto ha usado en-US de forma atómica.',
  'doctor.locale.fallbackInherited': 'El locale efectivo {locale} no ha podido resolver un catálogo completo y seguro; el texto de producto ha usado en-US de forma atómica. Hereda el locale del repositorio.',
  'doctor.locale.resolved': 'El locale efectivo {locale} se resuelve mediante la ruta de catálogo {source}.',
  'doctor.locale.resolvedInherited': 'El locale efectivo {locale} se resuelve mediante la ruta de catálogo {source}. Hereda el locale del repositorio.',
  'doctor.locale.dynamicAction': 'Comprueba que el agente de planificación/idioma está disponible y devuelve texto localizado válido; después, vuelve a ejecutar doctor.',
  'doctor.configuration.valid': 'La configuración de setup es válida.',
  'doctor.configuration.invalid': 'La configuración de setup tiene {count} error(es) de validación.',
  'doctor.configuration.action': 'Corrige la configuración de setup y vuelve a ejecutar doctor.',
  'doctor.repositoryRoot.valid': 'El directorio actual es la raíz del repositorio.',
  'doctor.repositoryRoot.invalid': 'El directorio actual no es la raíz del repositorio.',
  'doctor.repositoryRoot.unverified': 'No se ha podido verificar la raíz del repositorio.',
  'doctor.repositoryRoot.action': 'Ejecuta doctor desde la raíz del repositorio Git de destino.',
  'doctor.workflow.skipped': 'Se ha omitido la comparación de workflows porque la configuración de setup no es válida.',
  'doctor.workflow.matches': 'Coincide con la plantilla de setup instalada.',
  'doctor.workflow.drift': 'El workflow local está en estado {state}.',
  'doctor.workflow.unverified': 'No se han podido comparar los workflows gestionados.',
  'doctor.workflow.configurationAction': 'Corrige la configuración de setup y vuelve a ejecutar doctor.',
  'doctor.workflow.repairAction': 'Ejecuta setup para reparar este workflow gestionado.',
  'doctor.workflow.unverifiedAction': 'Comprueba los workflows locales y vuelve a ejecutar doctor.',
  'doctor.setupPat.valid': 'El PAT de setup es válido.',
  'doctor.setupPat.invalid': 'El PAT de setup no es válido.',
  'doctor.setupPat.unverified': 'No se ha podido validar el PAT de setup.',
  'doctor.setupPat.replaceAction': 'Sustituye el PAT de setup y vuelve a ejecutar doctor.',
  'doctor.setupPat.unverifiedAction': 'Comprueba el PAT de setup y el acceso de red, y vuelve a ejecutar doctor.',
  'doctor.mergeQueue.skipped': 'No se ha inspeccionado la preparación de merge queue porque la configuración de setup no es válida.',
  'doctor.mergeQueue.skippedAction': 'Corrige los errores de configuración indicados y vuelve a ejecutar doctor.',
  'doctor.mergeQueue.unverified': 'No se ha podido inspeccionar la preparación de merge queue.',
  'doctor.mergeQueue.unverifiedAction': 'Comprueba el acceso a la política de rama y vuelve a ejecutar doctor.',
  'doctor.scope.unverified': 'No se han podido inspeccionar los ámbitos de recursos de GitHub Actions.',
  'doctor.scope.unverifiedAction': 'Comprueba el acceso del PAT de setup a los metadatos de Actions del repositorio y la organización, y vuelve a intentarlo.',
  'doctor.scope.readable': 'Los ámbitos de recursos de GitHub Actions son legibles.',
  'doctor.scope.unavailable': 'Algunos ámbitos de recursos de GitHub Actions de la organización no están disponibles.',
  'doctor.scope.grantAction': 'Concede al PAT de setup el acceso necesario a los metadatos de Actions de la organización.',
  'doctor.variable.missing': 'Falta la Variable.',
  'doctor.variable.configured': 'La Variable está configurada en el ámbito {scope}.',
  'doctor.variable.preserved': 'La Variable difiere, pero se conserva intencionadamente en el ámbito {scope}.',
  'doctor.variable.different': 'La Variable difiere de la configuración de setup esperada.',
  'doctor.variable.action': 'Ejecuta setup para reconciliar esta Variable.',
  'doctor.secretMetadata.readable': 'Los metadatos de Secrets de GitHub Actions son legibles.',
  'doctor.credential.group.runnerRequired': 'No hay un Secret alternativo configurado; la autenticación del runner debe satisfacer este grupo.',
  'doctor.credential.group.missing': 'No hay ninguna credencial alternativa disponible.',
  'doctor.credential.group.healthy': 'Al menos una credencial alternativa es válida.',
  'doctor.credential.group.invalid': 'Todas las credenciales alternativas disponibles son inválidas.',
  'doctor.credential.group.unverified': 'Hay una credencial alternativa, pero su estado remoto no está disponible.',
  'doctor.credential.group.action': 'Configura y valida una credencial para este grupo de requisitos.',
  'doctor.credential.missing': 'Falta el Secret requerido.',
  'doctor.credential.valid': 'El estado de la credencial es válido.',
  'doctor.credential.invalid': 'El estado de la credencial es inválido.',
  'doctor.credential.unverifiable': 'El estado de la credencial no se puede verificar automáticamente.',
  'doctor.credential.unverified': 'El Secret está presente, pero su estado remoto no está disponible.',
  'doctor.credential.action': 'Configura o sustituye {name} y vuelve a ejecutar la comprobación de credenciales.',
  'doctor.skipped.scope': 'La inspección de ámbitos requiere un PAT de setup válido.',
  'doctor.skipped.scopeAction': 'Sustituye el PAT de setup.',
  'doctor.skipped.variables': 'No se han podido comprobar las Variables.',
  'doctor.skipped.secrets': 'No se han podido comprobar los metadatos de Secrets.',
  'doctor.skipped.credentials': 'No se ha podido comprobar el estado de las credenciales.',
  'doctor.skipped.resourceAction': 'Resuelve el check bloqueante y vuelve a ejecutar doctor.',
  'doctor.mergeQueue.configureSupportedAction': 'Configura un productor de merge queue compatible o elige otro modo de reconciliación.',
  'doctor.mergeQueue.repairOrAttestAction': 'Repara o atestigua cada productor obligatorio de merge queue.',
  'doctor.mergeQueue.selectedMode': 'El modo seleccionado es {mode}; este destino no necesita evidencia de productores de merge queue.',
  'doctor.mergeQueue.ready': 'Listo. {verified} productor(es) obligatorio(s) verificados automáticamente y {attested} cubiertos por atestación exacta.',
  'doctor.mergeQueue.targetUnverified': 'No se ha podido inspeccionar la política del destino porque ha fallado la petición al proveedor.',
  'doctor.mergeQueue.targetUnverifiedAction': 'Comprueba los permisos del PAT de setup y la política de la rama de destino, y vuelve a intentarlo.',
  'doctor.mergeQueue.activeRelease': 'Las ramas de release activas se descubren dinámicamente y se revalidan antes de crear una rama o pull request de reconciliación de hotfix.',
  'doctor.mergeQueue.staleAttestation': 'Esta atestación exacta no coincide con ningún check obligatorio observado en producción o desarrollo.',
  'doctor.mergeQueue.staleAttestationAction': 'Elimina la atestación obsoleta o corrige la identidad exacta del check.',
  'doctor.mergeQueue.producer': '{verdict}: {state}',
  'doctor.mergeQueue.producerAction': 'Configura o atestigua exactamente este productor obligatorio.',
});

function messages(
  doctor: Readonly<Record<DoctorOnlyMessageId, CatalogMessage>>,
  mergeQueue: Readonly<Record<MergeQueueMessageId, CatalogMessage>>,
  approval: Readonly<Record<ApprovalDoctorMessageId, CatalogMessage>>,
): Readonly<Record<SetupDoctorMessageId, CatalogMessage>> {
  return Object.freeze({ ...doctor, ...mergeQueue, ...approval });
}

export const ENGLISH_SETUP_DOCTOR_DEFINITION: MessageCatalogDefinition<SetupDoctorMessageId> = Object.freeze({
  version: MESSAGE_CATALOG_VERSION,
  locale: 'en-US',
  compatibleBaseLanguage: 'en',
  messages: messages(ENGLISH_DOCTOR_MESSAGES, ENGLISH_MERGE_QUEUE_MESSAGES, ENGLISH_APPROVAL_DOCTOR_MESSAGES),
});

export const SPANISH_SETUP_DOCTOR_DEFINITION: MessageCatalogDefinition<SetupDoctorMessageId> = Object.freeze({
  version: MESSAGE_CATALOG_VERSION,
  locale: 'es-ES',
  compatibleBaseLanguage: 'es',
  messages: messages(SPANISH_DOCTOR_MESSAGES, SPANISH_MERGE_QUEUE_MESSAGES, SPANISH_APPROVAL_DOCTOR_MESSAGES),
});

export const SETUP_DOCTOR_CATALOG_DEFINITIONS = Object.freeze([
  ENGLISH_SETUP_DOCTOR_DEFINITION,
  SPANISH_SETUP_DOCTOR_DEFINITION,
]);

export function resolveStaticSetupDoctorCatalog(locale = 'en-US'): SetupDoctorMessageCatalog {
  return resolveStaticMessageCatalogView(
    locale,
    ENGLISH_SETUP_DOCTOR_DEFINITION,
    SETUP_DOCTOR_CATALOG_DEFINITIONS,
  );
}

export function resolveSetupDoctorCatalog(
  locale: string,
  configuration: Readonly<AgentConfiguration> | undefined,
  resolver: MessageCatalogResolutionPort | undefined,
): Promise<SetupDoctorMessageCatalog> {
  return resolveMessageCatalogView(
    locale,
    SETUP_DOCTOR_MESSAGE_IDS,
    ENGLISH_SETUP_DOCTOR_DEFINITION,
    SETUP_DOCTOR_CATALOG_DEFINITIONS,
    configuration,
    resolver,
  );
}
